### ISSUE TITLE
Wallhaven out of alpha - updated what I thought it needed but still not working.

### ISSUE THREAD

**Issue by wredwards** [saurabhan/Wallhaven-dl#14]
No matter what I update in response to how the site pages are now named after coming out of alpha I seem to get the same response.

Login successful.
Fetching collection ids...
Traceback (most recent call last):
  File "wl_fav_dl_spec.py", line 149, in <module>
    main()
  File "wl_fav_dl_spec.py", line 141, in main
    for collection in collection_ids:
  File "wl_fav_dl_spec.py", line 59, in fetch_collections
    collections = favs_soup.find('ul', class_='blocklist collections-list').find_all('li')
AttributeError: 'NoneType' object has no attribute 'find_all'

Is there a way to increase buffer size as well?

**Comment by Tempest042** [comment]
I have updated the project to work with Wallhaven now its out of Alpha.
I only did some minor testing, let me know if you have any Issues.
Please find my fork here: https://github.com/Tempest042/Wallhaven-dl

**Comment by Tempest042** [comment]
Please refer to my pull request here:
https://github.com/saurabhan/Wallhaven-dl/pull/16/commits/9c4fdf121d1bbed8053be53ddf3cf100f0cda37e

The changes I make in the commit will make it use the new API.
You will need to replace the "YourAPIKeyHere" with your own API key which you can get by creating a Wallhaven Account.

It also has the added benefit of getting the full Image Path from the API, so the script no longer has to guess the file extension.

Please let me know if there are any Issues, I only tested it breifly,

**Comment by wredwards** [comment]
Thank You - works great - I've only been doing my favorites but figured out if I do the search by the id# it pulls as expected.  You are wonderful!
