### ISSUE TITLE
Save wallpapers in directories named by input?

### ISSUE THREAD

**Issue by hamensman** [saurabhan/Wallhaven-dl#26]
Not really an issue, but I have a question.

The script saves all wallpapers in the `Wallhaven` directory (which is in your working directory). How could I save them in directories named based on what I input?

For instance, if I enter `category`, `anime`, `swf`, I want the wallpapers to save to `anime/sfw/` [as in, `sfw` directory is inside `anime` directory] or just `anime/`.

If I enter `latest`, I want the wallpapers saved to `latest/`.

Or if I enter `search`, `pokemon`, I want the wallpapers to be saved to `pokemon/`

**Comment by Tempest042** [comment]
The following code will more or less do what you want.
If you search for `pokemon`, it will be saved to `pokemon/`
If you enter `latest `it will appear in `latest/`
If you enter `category`, `anime `, `sfw` it will be saved to `anime-sfw/`

Here is the modified code:

`########################################################
#        Program to Download Wallpapers from           #
#                  alpha.wallhaven.cc                  #
#                                                      #
#                 Author - Saurabh Bhan                #
#                                                      #
#                  Dated- 26 June 2016                 #
#                 Update - 11 June 2019                #
########################################################

import os
import getpass
import re
import requests
import tqdm
import time
import urllib
import json

BASEURL=""
cookies=dict()

global APIKEY
APIKEY = 'Enter Your APIKEY Here'

def category():
    global BASEURL
    global DIRECTORY
    print('''
    ****************************************************************
                            Category Codes
    all     - Every wallpaper.
    general - For 'general' wallpapers only.
    anime   - For 'Anime' Wallpapers only.
    people  - For 'people' wallapapers only.
    ga      - For 'General' and 'Anime' wallapapers only.
    gp      - For 'General' and 'People' wallpapers only.
    ****************************************************************
    ''')
    ccode = input('Enter Category: ').lower()
    ctags = {'all':'111', 'anime':'010', 'general':'100', 'people':'001', 'ga':'110', 'gp':'101' }
    ctag = ctags[ccode]

    print('''
    ****************************************************************
                            Purity Codes
    sfw     - For 'Safe For Work'
    sketchy - For 'Sketchy'
    nsfw    - For 'Not Safe For Work'
    ws      - For 'SFW' and 'Sketchy'
    wn      - For 'SFW' and 'NSFW'
    sn      - For 'Sketchy' and 'NSFW'
    all     - For 'SFW', 'Sketchy' and 'NSFW'
    ****************************************************************
    ''')
    pcode = input('Enter Purity: ')
    ptags = {'sfw':'100', 'sketchy':'010', 'nsfw':'001', 'ws':'110', 'wn':'101', 'sn':'011', 'all':'111'}
    ptag = ptags[pcode]

    BASEURL = 'https://wallhaven.cc/api/v1/search?apikey=' + APIKEY + "&categories=" +\
        ctag + '&purity=' + ptag + '&page='
    DIRECTORY = ccode + "-" + pcode

def latest():
    global BASEURL
    global DIRECTORY
    print('Downloading latest')
    topListRange = '1M'
    BASEURL = 'https://wallhaven.cc/api/v1/search?apikey=' + APIKEY + '&topRange=' +\
    topListRange + '&sorting=toplist&page='
    DIRECTORY = 'latest'

def search():
    global BASEURL
    global DIRECTORY
    query = input('Enter search query: ')
    BASEURL = 'https://wallhaven.cc/api/v1/search?apikey=' + APIKEY + '&q=' + \
        urllib.parse.quote_plus(query) + '&page='
    DIRECTORY = query

def downloadPage(pageId, totalImage):
    url = BASEURL + str(pageId)
    urlreq = requests.get(url, cookies=cookies)
    pagesImages = json.loads(urlreq.content);
    pageData = pagesImages["data"]

    for i in range(len(pageData)):
        currentImage = (((pageId - 1) * 24) + (i + 1))

        url = pageData[i]["path"]
        
        filename = os.path.basename(url)

        os.makedirs(DIRECTORY, exist_ok=True)
        osPath = os.path.join(DIRECTORY, filename)
        if not os.path.exists(osPath):
            imgreq = requests.get(url, cookies=cookies)
            if imgreq.status_code == 200:
                print("Downloading : %s - %s / %s" % (filename, currentImage , totalImage))
                with open(osPath, 'ab') as imageFile:
                    for chunk in imgreq.iter_content(1024):
                        imageFile.write(chunk)
            elif (imgreq.status_code != 403 and imgreq.status_code != 404):
                print("Unable to download %s - %s / %s" % (filename, currentImage , totalImage))
        else:
            print("%s already exist - %s / %s" % (filename, currentImage , totalImage))

def main():
    Choice = input('''Choose how you want to download the image:
    Enter "category" for downloading wallpapers from specified categories
    Enter "latest" for downloading latest wallpapers
    Enter "search" for downloading wallpapers from search
    Enter choice: ''').lower()
    while Choice not in ['category', 'latest', 'search']:
        if Choice != None:
            print('You entered an incorrect value.')
        choice = input('Enter choice: ')

    if Choice == 'category':
        category()
    elif Choice == 'latest':
        latest()
    elif Choice == 'search':
        search()

    pgid = int(input('How Many pages you want to Download: '))
    totalImageToDownload = str(24 * pgid)
    print('Number of Wallpapers to Download: ' + totalImageToDownload)
    for j in range(1, pgid + 1):
        downloadPage(j, totalImageToDownload)

if __name__ == '__main__':
    main()`

**Comment by hamensman** [comment]
Thanks!

For the directory names with `search`, how would I have spaces and special characters (slash, apostrophe, colon, etc.) converted to underscore?

E.g., search `final fantasy`, saved to `final_fantasy`. Search `fate/stay night`, saved to `fate_stay_night`.

**Comment by Tempest042** [comment]
To replace spaces and special characters with an underscore replace line 79 of the modified file with 
`DIRECTORY = re.sub('[^0-9a-zA-Z]+', '_', query)` 
Now only digits, uppercase and lowercase alphabet will remain, anything else will be replaced by an underscore.

Here is the updated modified code:
[wallhaven-customfolders-fixedSearch.txt](https://github.com/saurabhan/Wallhaven-dl/files/7270960/wallhaven-customfolders-fixedSearch.txt)

**Comment by hamensman** [comment]
Works perfectly! Thanks for your help! Keep up the good work!
